import TermAndCondation from '../../screens/appside/termAndCondation';
import PrivacyPolicy from '../../screens/appside/privacyPolicy';
import Notification from '../../screens/appside/notification';
import Matched from '../../screens/appside/matched';
import ScheduleWorkout from '../../screens/appside/scheduleWorkout';
import SettingScreen from '../../screens/appside/setting';
import EditProfile from '../../screens/appside/editProfile';
import Workout from '../../screens/appside/workout';
import SwipesUpgrade from '../../screens/appside/swipesUpgrade';
import UpgradePlan from '../../screens/appside/upgradePlan';
import Payment from '../../screens/appside/payment';
import PaymentDone from '../../screens/appside/pymentDone';
import VerifyAccount from '../../screens/appside/verifyAccount';
import VerifyAccountImage from '../../screens/appside/verifyAccountImage';
import DocumentDone from '../../screens/accountCompletion/documentCompelete';
import Conversion from '../../screens/appside/conversion';
import ScheduleWorkoutDone from '../../screens/appside/scheduleWorkoutDone/inedx';
import WorkoutLocation from '../../screens/appside/workoutLocation';
import ScheduleClander from '../../screens/appside/scheduleClander';
import VideoCalling from '../../screens/appside/videoCalling';
import FavouriteOne from '../../screens/appside/favouriteOne';
export {TermAndCondation};
export {PrivacyPolicy};
export {Notification};
export {Matched};
export {ScheduleWorkout};
export {SettingScreen};
export {EditProfile};
export {Workout};
export {SwipesUpgrade};
export {UpgradePlan};
export {Payment};
export {PaymentDone};
export {VerifyAccount};
export {VerifyAccountImage};
export {DocumentDone};
export {Conversion};
export {ScheduleWorkoutDone};
export {WorkoutLocation};
export {ScheduleClander};
export {VideoCalling};
export {FavouriteOne};
